- name: Test connectivity
  hosts: all
  tasks:
  - name: Ping the host
    ping: 
  - name: Echo a message
    debug:
     msg: "User running this task is {{ansible_user}}, IP address s {{ansible_host}}"
  - name: Time and date on the server
    shell:
     cmd: echo "The current time/date is $(date)"